# _config.yml

# required, replace with your own information -----
title: 120 Life
author: Sara Gong
description: > 
  长期主义｜理性生活｜健康｜成长｜走向120岁的人生系统
baseurl: ""

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  
#---------------------------------------------------

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock

